/**
 * Autoreq - A node program that generate a single .js file requiring all files that matches a given file name
 * Copyright Rafael Salguero Iturrios
 *  
 */

import fs = require("fs");
import path = require("path");

/**Format a two digit number */
function Format2Digit(n: number): string {
    return n < 10 ? "0" + n.toString() : n.toString();
}

var args = process.argv.slice(2);
if (args.length < 1) {
    //Show console help:
    console.log("Generate a single .js that sets a global variable with the current date and time. Usefull for versioning web applications");
    console.log();
    console.log("Syntax: node dateversion.js fileName [variable]");
    console.log();
    console.log("Arguments:");
    console.log('- fileName : The file name to match including extension. Can be "*.js", "*.ts" or "*" to include all files');
    console.log('- variable : The name of the global variable to assign. The default variable is: "app.version"');
    console.log();
    console.log("Example:");
    console.log('node dateversion.js "version.js" "app_version"');

    console.log();
    console.log("Output:");
    console.log("var app = app || { }");
    console.log("app.version = '20160426T173732'");
}
else {
    var fileName = args[0];
    var variable = args.length > 1 ? args[1] : "app.version";

    var date = new Date();
    var version = date.getFullYear().toString() + Format2Digit(date.getMonth() + 1) + Format2Digit(date.getDay()) + "T" + Format2Digit(date.getHours()) + Format2Digit(date.getMinutes()) + Format2Digit(date.getSeconds());
    var data =
        "//This file was autogenerated by dateversion with the following parameters:" +
        "\n//fileName   : " + fileName +
        "\n//variable   : " + variable;

    var vars = variable.split(".");
    var fullName = "";
    for (var i = 0; i < vars.length; i++) {
        var n = vars[i];
        fullName = fullName == "" ? n : fullName + "." + n;
        data += "\n";
        if (i == 0) {
            if (vars.length == 1) {
                //Theres only one variable
                data += "var " + n + " = '" + version + "'";
            }
            else {
                //There are more than one variable
                data += "var " + n + " = " + n + " || { }";
            }
        }
        else if (i == (vars.length - 1)) {
            data += fullName + " = '" + version + "'";
    }
        else {
            data += fullName + " = " + "(" + fullName + ") || { }";
        }
        data += ";";
    }

    fs.writeFileSync(fileName, data);
}


